### ISSUE TITLE
Support for workspaces?

### ISSUE THREAD

**Issue by gabel0287** [uber/astro#22]
Does astro support checking out a new terraform workspace to run plan?

**Comment by gabel0287** [comment]
Terraform workspaces is essentially equivalent to your use of environment but built into terraform.  We use the same terraform files but checkout workspace prod or staging before running terraform apply to provision the respective environments.  https://www.terraform.io/docs/state/workspaces.html

We would like to be able to use the built in workspaces instead of a separate environment variable. 

Given a config: 

```
  - name: vpc
    path: core/vpc
    remote:
      backend_config:
        bucket: acme-terraform-states
        key: "{{.aws_region}}/vpc.tfstate"
        region: us-east-1
    workspaces:
      - prod
      - staging
```

Running `astro plan --workspace staging` would result in:

```cd core/vpc -> terraform workspace select staging -> terraform plan```

Running `astro plan ` would result in:

```cd core/vpc -> terraform workspace select staging -> terraform plan``` AND
```cd core/vpc -> terraform workspace select prod -> terraform plan```
